TaskBoardWebApp/Models/Artifact.cs
namespace TaskBoardWebApp.Models
{
    public class Artifact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Rare { get; set; }    
        public string Description { get; set; }
        public string Image { get; set; }
        public int Power { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
    }
}

TaskBoardWebApp/Models/Character.cs
using System.ComponentModel.DataAnnotations.Schema;
namespace TaskBoardWebApp.Models
{
    public class Character
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Level { get; set; }
        public int Experience { get; set; }
        public DateTime CreateDate { get; set; }
        [ForeignKey("UserId")]
        public int UserId { get; set; }
        public virtual ICollection<Artifact> Artifacts { get; set; }
        public virtual User User { get; set; }
    }
}

TaskBoardWebApp/Models/ErrorViewModel.cs
namespace TaskBoardWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TaskBoardWebApp/Models/Rating.cs
namespace TaskBoardWebApp.Models
{
    public class Rating
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public int Score { get; set; }
        public DateTime RatingDate { get; set; }
        public virtual Task Task { get; set; }
    }
}

TaskBoardWebApp/Models/Task.cs
namespace TaskBoardWebApp.Models
{
    public class Task
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime ExecuteDate { get; set; }
        public bool IsExecute { get; set; }
        public int Experience { get; set; }
        public int Rating { get; set; }

        public virtual Character Character { get; set; }
        public virtual TaskCategory Category { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}

TaskBoardWebApp/Models/TaskCategory.cs
namespace TaskBoardWebApp.Models
{
    public class TaskCategory
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public virtual ICollection<Task> Tasks { get; set;}
    }
}

TaskBoardWebApp/Models/User.cs
namespace TaskBoardWebApp.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
    }

}

TaskBoardWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TaskBoardWebApp.Models;

namespace TaskBoardWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TaskBoardWebApp/Infrastructure/Components/CharacterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TaskBoardWebApp.Infrastructure.Components
{
    public class CharacterViewComponent: ViewComponent
    {
        private readonly DataContext _context;

        public CharacterViewComponent(DataContext context)
        {
            _context = context;
        }   
        
        public async Task<IViewComponentResult> InvokeAsync() => View(await _context.Characters.ToListAsync());
    }
}

TaskBoardWebApp/Infrastructure/Components/TaskCategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TaskBoardWebApp.Infrastructure.Components
{
    public class TaskCategoryViewComponent: ViewComponent
    {
        private readonly DataContext _context;

        public TaskCategoryViewComponent(DataContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync() => View(await _context.Categories.ToListAsync());
    }
}

TaskBoardWebApp/Views/Shared/Components/Characters/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">1123312321321</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TaskBoardWebApp/Views/Shared/Components/TaskCategories/Default.cshtml
@model TaskCategory

<ul class="list-group">
    <li class="list-group-item">
        <a class="nav-link text-dark" asp-controller="Categories" asp-action="Index">All Categories</a>
    </li>

    <li class="list-group-item" foreach="var item in Model">
        <a class="nav-link text-dark" asp-controller="Categories" asp-action="Details" asp-route-categoryId="@Model.Id">@Model.Category</a>
    </li>
</ul>

TaskBoardWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskBoardWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskBoardWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskBoardWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="col-3">
               <vc:task-category />
            </div>
            <div class="row">
                <div class="col">
                    <partial name="_NotificationPartial"/>
                    @RenderBody()
                </div>
            </div>
            
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TaskBoardWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskBoardWebApp/Views/Shared/_NotificationPartial.cshtml
@if(TempData["Success"] != null)
{
    <div class="alert alert-success.notification">
        @TempData["Success"]  
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger.notification">
        @TempData["Error"]
    </div>
}